name: ci

on:
  push:
    branches:
      - master

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: My Step
        run: |
          if [ "$(curl -s -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" -H "Accept: application/vnd.github.antiope-preview+json" \
          https://api.github.com/repos/C0083M/Module_4_Project/actions/runs | jq -r '.workflow_runs[0].conclusion')" != "success" ]; then
            echo "CI workflow did not succeed. Merging is not allowed."
            exit 1
          fi

        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
