name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install required packages
      run: |
        python -m pip install pytest
        python -m pip install requests
      working-directory: ./

    - name: Run Pytest
      run: |
        pytest tests/test.py
      working-directory: Module-4-Project/tests/test.py
