name: Production Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check CI workflow result
        id: ci_result
        run: echo "CI workflow status is ${{ github.event.workflow_run.conclusion }}"
        continue-on-error: true

      - name: Deploy to Vercel
        if: steps.ci_result.outputs.ci_result == 'success'
        run: |
          echo "Deployment approved. Deploying to Vercel."
          # Actual deployment steps to Vercel
        else
          run: |
            echo "Deployment denied. CI workflow failed."
            # Additional steps or notifications can be added here

      # Add more deployment steps or notifications as needed
